pull request for issue #65
laminas/laminas-cache-storage-adapter-filesystem pull request #73
Opened 2023-09-05 11:26 UTC by tck

2023-09-05 19:45 UTC, Ocramius requested changes

2023-09-05 19:45 UTC, Ocramius commented on src/FilesystemOptions.php
> +        }
Needs some sort of test / reproducer, IMO.

2023-09-06 18:20 UTC, boesing commented on src/FilesystemOptions.php
> +        }
I would suggest creating a directory in that test, change permissions to read-only using `chmod` and pass that to `ini_set` to modify sys temp dir for that test. 

Having something like `try {} finally {}` to restore temp dir back to default to ensure test does not introduce side-effects to other tests.

2023-11-27 08:43 UTC, sbenischke commented
Any update on this topic?

In my opinion the `sys_tmp_dir` should be used as a fallback **after** the try to initialize the configured directory. So at least there is the possibility to get this adapter working, if the `sys_tmp_dir` is neither readable or writeable.

2023-11-29 10:57 UTC, boesing commented
Once the requested changes are applied, we can move on.
Feel free to use these changes to create a new PR with added test(s) or wait until the author is responding.

2024-01-26 07:37 UTC, bcremer commented on src/FilesystemOptions.php
> +        }
`sys_temp_dir` is of type `PHP_INI_SYSTEM` and thus cannot be set during runtime via `ini_set`.

2024-01-26 08:01 UTC, bcremer commented
I stumbled about this problem during a `docker run  --read-only` deployment of an mezzio application.

I came up with the same fix as @tck. Building a reproducer as phpunit testcase is tricky because `sys_tmp_dir` cannot be modified during runtime, see: https://github.com/laminas/laminas-cache-storage-adapter-filesystem/pull/73#discussion_r1467308698.


A standalone reproducer looks like the following:

```php
<?php

require __DIR__  . '/vendor/autoload.php';

putenv('TMPDIR=/fasel');

// the following will throw an exception:
new \Laminas\Cache\Storage\Adapter\FilesystemOptions(['cacheDir' => '/tmp']);
```

```
PHP Fatal error:  Uncaught Laminas\Cache\Exception\InvalidArgumentException: Cache directory '/fasel' not found or not a directory in /home/apidev/current/laminas-cache-storage-adapter-filesystem/src/FilesystemOptions.php:440
```

2024-01-26 11:17 UTC, boesing commented
Might be possible to modify the `tmpdir` setting via `php` CLI command when running a specific test group.

We could create a test, add a group to it, use that group in `additional_checks` when running `php vendor/bin/phpunit` along with the `-d` parameter to modify the temp dir target, add a check to that test that it skips the execution when tmp directory is readable and that should do the trick, no?

The check in the test could look like:

```php
if (is_writable(sys_get_temp_dir())) { 
    self::markAsRisky(); 
    self::markTestSkipped('Test has to be executed in read-only environment...');
}
```

2024-01-26 16:30 UTC, boesing commented on src/FilesystemOptions.php
> +        }
I am not sure if this is a tmpdir only issue. Whenever a directory is used without write-permissions, that could lead to problems, no?

2024-01-29 06:43 UTC, bcremer commented
@boesing Implemented in a separate PR: https://github.com/laminas/laminas-cache-storage-adapter-filesystem/pull/84

2024-07-10 12:52 UTC, boesing commented
Superseded by #84

2024-07-10 12:52 UTC, closed without merging